name: namma_wallet
description: "Namma Wallet is an open-source project developed by the community
  members of Namma Flutter"
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: "3.9.0"
  flutter: "3.35.2"

dependencies:
  ai_barcode_scanner: ^7.0.0
  card_stack_widget: ^0.1.6
  cupertino_icons: ^1.0.8
  dart_mappable: ^4.6.0
  dotted_border: ^3.1.0
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_gemma: ^0.11.9
  flutter_svg: ^2.2.1
  get_it: ^9.0.5
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  google_mlkit_text_recognition: ^0.15.0
  home_widget: ^0.8.0
  http: ^1.5.0
  image: ^4.3.0
  intl: ^0.20.2
  listen_sharing_intent:
    git:
      url: https://github.com/Zverik/receive_sharing_intent
  path: ^1.9.1
  path_provider: ^2.1.5
  pdfrx: ^2.2.16
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  syncfusion_flutter_pdf: ^31.1.19
  table_calendar: ^3.1.2
  talker_flutter: ^5.0.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.0
  change_app_package_name: ^1.5.0
  dart_mappable_builder: ^4.6.0
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/

flutter_gen:
  output: lib/src/features/common/generated/
  line_length: 80
