name: namma_wallet
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  ai_barcode_scanner: ^7.0.0
  card_stack_widget: ^0.1.6
  cupertino_icons: ^1.0.8
  dart_mappable: ^4.6.0
  dotted_border: ^3.1.0
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_gemma: ^0.10.5
  flutter_svg: ^2.2.1
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  home_widget: ^0.8.0
  intl: ^0.20.2
  path: ^1.9.1
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  syncfusion_flutter_pdf: ^31.1.19
  table_calendar: ^3.1.2
  uuid: ^4.5.1
  listen_sharing_intent:
    git:
      url: https://github.com/Zverik/receive_sharing_intent

dev_dependencies:
  build_runner: ^2.4.0
  change_app_package_name: ^1.5.0
  dart_mappable_builder: ^4.6.0
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_gen:
  output: lib/src/features/common/generated/
  line_length: 80
