name: flutter-analyze-commenter

on: pull_request # Only supports run by pull request

jobs:
  flutter-analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Write permission is required to add comments on a PR
    steps:
      - uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - run: flutter pub get

      # Run flutter analyze with --write option
      - run: flutter analyze --write=flutter_analyze.log

      # Use flutter-analyze-commenter
      - if: ${{ !cancelled() }} # Required to run this step even if failure
        uses: yorifuji/flutter-analyze-commenter@v1
        with:
          analyze-log: flutter_analyze.log # file path for analyze log, if multiple files, separated by commas
          verbose: true # verbose output (optional)
