name: flutter-format-and-analyze

on:
  pull_request:
    branches:
      - main # Only PRs targeting main branch

jobs:
  flutter-format-and-analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Check dart format
        id: format_check
        run: |
          set +e
          dart format --set-exit-if-changed .
          echo "exit_code=$?" >> $GITHUB_OUTPUT
          exit 0  # keep workflow running so we can comment

      - name: Comment if formatting failed
        if: ${{ steps.format_check.outputs.exit_code != 0 }}
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ‚ùå **Formatting check failed**
            Please run:
            ```bash
            fvm dart format .
            ```

            or 

            ```bash
            dart format .
            ```
            And push the updated files.

      - name: Run flutter analyze (write log)
        if: ${{ steps.format_check.outputs.exit_code == 0 }}
        run: flutter analyze --write=flutter_analyze.log

      - name: Comment analyze results
        if: ${{ steps.format_check.outputs.exit_code == 0 && !cancelled() }}
        uses: yorifuji/flutter-analyze-commenter@v1
        with:
          analyze-log: flutter_analyze.log
          verbose: true
